development:
  adapter: postgresql
  encoding: unicode
  database: new_db_youth
  host: localhost
  pool: 5
  username: devcache123
  password: 123456


# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
# development:
#   <<: *default
#   database: new_db_youth
#   username: devcache123
#   password: 123456
# test:
#   <<: *default
#   database: jiyouth_test
# production:
#   <<: *default
#   database: jiyouth_production